# autumn, autumn_night, bogster, bogster_light, carbonfox, nightfox, onedark, onedarker, starlight
theme = "nightfox"

[editor]
# export COLORTERM=truecolor
# cursorcolumn = true
cursorline = true
bufferline = "always"   # always | never | multiple
middle-click-paste = true
mouse = true
rulers = [80, 120]
true-color = true

[editor.file-picker]
hidden = false

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
G = "goto_file_end"

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
C = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", "insert_mode"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]
F11 = ["goto_previous_buffer"]
F12 = ["goto_next_buffer"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]
F11 = ["goto_previous_buffer"]
F12 = ["goto_next_buffer"]
